### ISSUE TITLE
Azure Vote go dependencies no longer exist

### ISSUE THREAD

**Issue by dtzar** [Azure-Samples/azure-service-operator-samples#42]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
These repositories no longer exist, therefore the application does not work.
https://github.com/Azure-Samples/azure-service-operator-samples/blob/480b78f57914e15caf85dcf53044beb7d1201597/azure-votes-sql/cmd/root.go#L24
https://github.com/Azure-Samples/azure-service-operator-samples/blob/480b78f57914e15caf85dcf53044beb7d1201597/azure-votes-postgresql/cmd/root.go#L17

### Expected/desired behavior
The samples function.

### OS and Version?
Windows 11 with WSL, Golang 1.20.6

**Comment by matthchr** [comment]
@super-harsh - did you fix this in #43? I think halfway fixed because we removed `azure-votes-sql`, but `azure-votes-postgresql` I think still will not work as the application has disappeared.

**Comment by super-harsh** [comment]
The [azure-votes-sql](https://github.com/Azure-Samples/azure-service-operator-samples/tree/480b78f57914e15caf85dcf53044beb7d1201597/azure-votes-sql) sample has been removed from the repository as it was a v1 sample. 
For [azure-votes-postgresql](https://github.com/Azure-Samples/azure-service-operator-samples/tree/master/azure-votes-postgresql), `"github.com/Azure/azure-votes-postgresql/pkg/azvotes"` references to the internal module and it exists [here](https://github.com/Azure-Samples/azure-service-operator-samples/tree/master/azure-votes-postgresql/pkg/azvotes) already.

**Comment by matthchr** [comment]
Closing as per the above.
